### ISSUE TITLE
swiftapply applied to the series rather than every element of the series

### ISSUE THREAD

**Issue by bharatvem** [jmcarpenter2/swifter#1]
Function:
def p(x):
    return len(x)

Dataframe:
	0	1
0	18873078	---\n- :search_id: 1177951\n :enabled: true\n...
1	18873090	---\n- :search_id: 2905539\n :enabled: true\n...
2	18873093	---\n- :search_id: 2669725\n :enabled: true\n...
3	18873095	---\n- :search_id: 43889736\n :enabled: true\...
4	18873097	---\n- :search_id: 44104532\n :enabled: true\...

l = swiftapply(f1[1],p)

print(l)  gives => length of rows of the column
385832

swiftapply doesn't work as expected to give the length of characters in the first column of the pandas DataFrame.

**Comment by jmcarpenter2** [comment]
Hi Bharat,

Thank you for raising this issue. It is definitely associated with the core workflow of swiftapply, which attempts use the vectorized form first before falling back to elementwise applies. I will look into how best to handle this issue shortly.

In the meantime, if you wish to use swiftapply for this kind of functionality, I would use the following formulation instead.

def p(x):
    return x.str.len()

**Comment by bharatvem** [comment]
Sure yes. x.str.len() would work, but I'm implementing a complex logic in that place. len(x) was just a placeholder for it. 😃

**Comment by jmcarpenter2** [comment]
I believe I resolved the bug here. The solution was to attempt to perform each function (vectorized, map_partitions, etc) on a sample and assert that the shape is appropriate. Otherwise, fall back to element-wise operations like normal. I hope this solution works for your use case and the community in general. Thank you very much for raising this issue Bharat, identifying this issue has significantly improved the generalizability and usefulness of the package.
