### ISSUE TITLE
Swifter incorrectly comparing results of pandas and dask applies

### ISSUE THREAD

**Issue by sann05** [jmcarpenter2/swifter#106]
Wrong comparison of 2 pandas Series

```
swifter==0.302
dask==2.14.0 
pandas==1.0.3
```

file **swifter.py:289**
 ```
self._validate_apply(
    tmp_df.equals(meta), error_message="Dask apply sample does not match pandas apply sample."
)
```

It compares 2 Series (in my case):
**meta** = (0, 0.002689316907153639) (1, 0.0020169299881876556) (2, 0.0021525252276455888) (0, 0.0023806118812282305) (1, 0.002263126767581785) (2, 0.0023925398049665803) (0, 0.002505102859306909) (1, 0.0019670994913228703) (2, 0.0020991911781853417) (0, 0.0023227029
**temp_df** = (0, 0.002689316907153639) (0, 0.001975845345081718) (0, 0.002583021140662563) (0, 0.0022234801671238607) (0, 0.0021956561811590993) (0, 0.0023227029344862734) (0, 0.0027618463320199546) (0, 0.0023806118812282305) (0, 0.002505102859306909) (1, 0.00196709949

tmp_df.equals(meta) -  False 
while 
tmp_df.sort_index().equals(meta.sort_index())  - True
tmp_df.sort_values().equals(meta.sort_values()) - True

Is it correct?

PS. There is a suggestion is to change tmp_df and meta name to more obvious name to understand which came from what part (e.g. dask_smpl_apply_df and pd_smpl_apply_df)
PSS. For some reason, Dask reduces the amount of partitions for the dataframe from 16 to 5

**Comment by jmcarpenter2** [comment]
Hi @sann05 ,

Thanks for raising this issue. This is a surprising issue, and one I hope to get to the bottom of. Towards that end, I appreciate you providing some context, but I'd like to ask for a bit more detail.

If possible, could you provide a reproducible code example that causes this issue to occur? Then I can really dive deep on the issue.

Re: PS - this is a good suggestion, I will likely incorporate these naming changes for clarity.
Re: PSS - what do you mean "reduces" the amount of partitions? Did you set the initial partitions using the `set_npartitions` command? When is the reduction in npartitions occurring?

Thanks,
Jason

**Comment by sann05** [comment]
Here is the link to the data:
https://drive.google.com/file/d/1aiEv39ZA3lxr92JPN959aREqY-9mh1zz/view?usp=sharing
Code example:
```python
from math import sqrt

import pandas as pd
import swifter

def distance_coordinates(lat_position, lon_position, lat_home, lon_home):
    return sqrt((lat_position - lat_home) ** 2 + (lon_position - lon_home) ** 2)


def exec_func():
    df = pd.read_csv('data_test.csv', header=0, index_col=0)
    df['hot_spot_distance'] = (
        df.swifter
            .allow_dask_on_strings(enable=True)
            .apply(
            lambda x: distance_coordinates(
                x['lat_position'], x['lon_position'],
                float(x['lat_zone']), float(x['lon_zone'])), axis=1)
    )


if __name__ == '__main__':
    exec_func()
```

**Comment by jmcarpenter2** [comment]
Hi @sann05 ,

I figured out what the issue was. Basically, the equality between dask and pandas was lost because of an indexing issue in the original csv. See the image below with repeated 0,1,2 indices on load into pandas.

![Screen Shot 2020-04-27 at 7 53 54 AM](https://user-images.githubusercontent.com/29585347/80386571-66b92580-885c-11ea-92a4-a93f9bb59979.png)

A simple solution that works currently is to reset the index before using pandas or swifter.

![Screen Shot 2020-04-27 at 7 55 38 AM](https://user-images.githubusercontent.com/29585347/80386644-805a6d00-885c-11ea-9e05-46c680c6895d.png)

![Screen Shot 2020-04-27 at 7 58 07 AM](https://user-images.githubusercontent.com/29585347/80386908-dc24f600-885c-11ea-87a4-ba9a59f1bf06.png)

However, you raise a really important point. **Swifter silently fails to improve performance when there are duplicate indices, i.e. the indices haven't been reset.** This needs to be handled better. I am curious what your opinion is. My thought is to raise a warning if someone tries to use swifter on a dataframe with duplicate indices, reminding them to reset before calling swifter. Let me know what kind of solution you think would be best, thanks!

Thanks for your input,
Jason

**Comment by sann05** [comment]
Thank you @jmcarpenter2  for your effort

I believe warning will be more than enough as we don't know if it a mistake or a requirement.

Best,
Aliaksandr

**Comment by jmcarpenter2** [comment]
Follow-up: resolving this issue in #108
