### ISSUE TITLE
Not found much difference between in pandas and swifter

### ISSUE THREAD

**Issue by hpshah123** [jmcarpenter2/swifter#113]
Hi,
Thanks for the amazing package.

But I have run the simple code to test pandas apply and swifter but I don't find any significant difference between two. Even, pandas work faster than the swifter. I have 5000000 records in a dataframe and I am running simple calculation on apply.
I have tried on both Linux and windows system. 
Python version 3.7
Windows 10
Linux - ubuntu
swifter - 0.286
pandas - 1.0.3
PFA file. 

[swifter_test (1).html.pdf](https://github.com/jmcarpenter2/swifter/files/4714724/swifter_test.1.html.pdf)

Please help me with this. what wrong I am doing?

**Comment by jmcarpenter2** [comment]
Hi @hpshah123 ,

Thanks for raising this issue. This really motivates me to write another blog post about how to write functions to best take advantage of swifter.

Here is how I recommend you rewrite your function:

```python
def func(a, b):
    return np.where(a > 50 or b > 75, True, False)
```

My machine was able to reduce processing time from 2 minutes to 28 seconds when using swifter and rewriting the function in that way.

![Screen Shot 2020-06-02 at 9 59 41 AM](https://user-images.githubusercontent.com/29585347/83547956-d2c02680-a4b7-11ea-8fd6-92c4e1125fdc.png)

You see, swifter can only optimize to a certain extent. The function you provided can only operate serially due to the series of control-flow if-else statements. By moving to `np.where`, swifter is able to take advantage of multi-processing with dask and cut down processing time by 4x.

I will take it as an action-item for myself to write another blog post explaining these nuances and the newer features of swifter.

Thanks!
Jason
