### ISSUE TITLE
Numba dependency

### ISSUE THREAD

**Issue by meakbiyik** [jmcarpenter2/swifter#114]
Hi there! Your package seems really neat and I would like to use it for my projects. Yet, it seems to have numba dependency that doesn't seem very necessary, and as I can't use numba for my purposes I was curious if there's any particular reason that it's included in the package?

**Comment by jmcarpenter2** [comment]
Hey @meakbiyik,

The numba dependency was added as a result of this issue: https://github.com/jmcarpenter2/swifter/issues/35

To be honest, I'm not sure that there's a good reason to have numba as a hard dependency. I understand that it is helpful when people want to use numba decorator for defining their apply function, but I agree with you that it should not be a hard dependency of swifter because that places additional constraints on package size and who can use the package.

I am thinking to remove the numba dependency and just add a note in the documentation regarding the use of numba functions for swifter applies. I will post an update here when a final decision is made or a new version if released that makes this change. Let me know if you (or anyone else in the community) have any additional thoughts/comments regarding this topic.

Thanks for bringing this to my attention,
Jason

**Comment by jmcarpenter2** [comment]
Hi @meakbiyik ,

Thanks so much for raising this point. I just released version `0.305`, which gracefully handles this situation regardless of whether or not `numba` is installed. If you don't have numba, it should work. If you do have numba, it should also work and still handle the `TypingError` from numba.

To uggrade please do either of `pip install swifter==0.305` or `pip install -U swifter`.

Thanks!
Jason
