### ISSUE TITLE
Issues when using swifter for geopandas

### ISSUE THREAD

**Issue by tfdgrand** [jmcarpenter2/swifter#123]
When working with GeoDataframes, I want to apply a function that adds the row's unique ID to the geometry class of each row. Much like [this example](https://github.com/Toblerity/Shapely/issues/618#issuecomment-408891713), I want to use the attribute for querying an STRtree of the geometries later on. 

The following function is used:

```
def add_uid(row):
    row["geometry"].uid = row["uid"]
    return row
```
and the function is applied to the geodataframe:
```
my_gdf = my_gdf.apply(add_uid, axis=1)
```
The result is as expected, with each of the geometries having its respective uid. 
When looking into optimizing this task, I tried implementing swifter as follows:

```
my_gdf = my_gdf.swifter.apply(add_uid, axis=1)
```

Outcome: the first 32 rows or so are fine (I assume sampled by swifter with regular apply), from then onwards "AttributeError: 'MultiPolygon' object has no attribute 'uid'".

What is going on? I know that Shapely is about geometries, and that user attributes are not preserved in some operations (e.g. when writing to a geofeather), but I would expect in this case that Swifter has the same behaviour as the regular .apply.

I'm using:
```
swifter==1.0.1
geopandas==0.7.0
```

**Comment by jmcarpenter2** [comment]
I hope this helps:

`swifter` has a new feature called `force_parallel` that allows you to skip straight to using dask to speed up performance (skipping the whole algorithm part).

Usage:
```python
my_gdf = my_gdf.swifter.force_parallel().apply(add_uid, axis=1)
```

Feel free to try it and let me know if it works.. if not you might not be able to use swifter to parallelize the job (possibly because assigning an attribute to a MultiPolygon object in parallel may not be possible??)

Thanks! And so sorry for the massive delay in response. Closing this thread due to inactivity but please reopen if further discussion could be helpful
