### ISSUE TITLE
Change in Custom Apply Functions 

### ISSUE THREAD

**Issue by msarafzadeh** [jmcarpenter2/swifter#139]
Ever since the older versions of swifter, I have been creating my own custom apply functions in the following format:
df=df.apply(preprocess_text,axis=1,args=())

and 
def pre_processtext(row):
    # do stuff . row['col']= something 
    return row

However now, it is returning for all row the same value in the first row.

**Comment by jmcarpenter2** [comment]
Hey @msarafzadeh thanks for flagging this. My guess is that this is because you are trying to assign a column value to the row inside of the function. More standard approach is as follows: 

```
def pre_processtext(row):
      # do stuff 
     return row (logic) something

df["col"] = df.apply(pre_processtext, axis=1, args=())
```

However, I believe I also know why this is causing issues and will see if the modin dependency is the source of the issue. Will follow-up when I know more.

**Comment by jmcarpenter2** [comment]
Removed modin dependency requirement in `swifter==1.0.8`, please check if this helps and let me know :)
