### ISSUE TITLE
Slow Performance of Swifter for Text Preprocessing

### ISSUE THREAD

**Issue by hadyan-tvlk** [jmcarpenter2/swifter#14]
Hi @jmcarpenter2,

Dear Swifter Folks,

Recently, i found the speed when using swifter is 5-10x slower than using vanilla pandas apply for case that the process is not vectorized (my case is doing text preprocessing).

The experiment is like this:

```python

import pandas as pd
import swifter

def clean_text(text):
    text = text.strip()
    text = text.replace(' ', '_')
    return text

N_rows = 7000000
df_data = pd.DataFrame([["i want to break free"]] * N_rows, columns=["text"])

%time df_data['text'] = df_data['text'].swifter.apply(clean_text)

%time df_data['text'] = df_data['text'].apply(clean_text)
```

Is it expected? let's have a discussion to make sure i'm not missing something. Thank you!

**Comment by jmcarpenter2** [comment]
Hey @hadyan-tvlk,

Thanks for identifying this issue! I too am noticing similar issues on non-vectorized string applies. To be perfectly honest, I have no clue why the underlying dask is processing large string applies slower than a regular large pandas apply.

I am currently experimenting with using a different parallel processing module specifically for string applies to see if I can resolve this shortcoming of the package. If you want, you are welcome to help identify other parallel processing packages that might be useful for me to implement in swifter for the case of string applies.

Thanks!

**Comment by jmcarpenter2** [comment]
I apologize for the delay in implementing a working solution for this issue. In order to avoid this being a reason not to use swifter in the short term, I have implemented a simple check if the input is a string. If the input is a series/dataframe of dtype string then we simply resort to pandas apply.

To be clear, this is a temporary solution until I can find a solution that will use parallelization to actually increase processing speed of text-based inputs.

**Comment by bkj** [comment]
Here's something that might be useful:
```

from concurrent.futures import ProcessPoolExecutor

chunk_fn = None
def parapply(x, fn, max_workers=32):
    global chunk_fn
    def chunk_fn(chunk):
        return [fn(c) for c in chunk]
    
    chunks = np.array_split(x.values, max_workers)
    with ProcessPoolExecutor(max_workers=max_workers) as ex:
        for g in ex.map(chunk_fn, chunks):
            yield from g

# --

from faker import Faker
fake = Faker()

# make random dates
dates = np.array([datetime.strftime(fake.date_between(start_date='today', end_date='+30y'), '%Y-%m-%d') for _ in range(1000)])
dates = np.hstack([dates.copy() for _ in range(400)])

# function to reformat dates
def fmt_date(d):
    return datetime.strftime(datetime.strptime(d, '%Y-%m-%d'), '%s')

# time python list comprehension
t = time()
z = [fmt_date(d) for d in dates]
time() - t
# 16.022817134857178

# time pandas apply
df = pd.DataFrame({'date' : dates})
t = time()
_ = df.date.apply(fmt_date)
time() - t
# 15.647859811782837

# time parapply
t = time()
_ = list(parapply(df.date, fmt_date))
time() - t
# 4.906782865524292
```

I don't get the same kind of speedup w/ the `clean_text` function above, but formatting dates is a reasonable example of an expensive string operation.

**Comment by bkj** [comment]
Here's something that might be useful:
```

from concurrent.futures import ProcessPoolExecutor

chunk_fn = None
def parapply(x, fn, max_workers=32):
    global chunk_fn
    def chunk_fn(chunk):
        return [fn(c) for c in chunk]
    
    chunks = np.array_split(x.values, max_workers)
    with ProcessPoolExecutor(max_workers=max_workers) as ex:
        for g in ex.map(chunk_fn, chunks):
            yield from g

# --

from faker import Faker
fake = Faker()

# make random dates
dates = np.array([datetime.strftime(fake.date_between(start_date='today', end_date='+30y'), '%Y-%m-%d') for _ in range(1000)])
dates = np.hstack([dates.copy() for _ in range(400)])

# function to reformat dates
def fmt_date(d):
    return datetime.strftime(datetime.strptime(d, '%Y-%m-%d'), '%s')

# time python list comprehension
t = time()
z = [fmt_date(d) for d in dates]
time() - t
# 16.022817134857178

# time pandas apply
df = pd.DataFrame({'date' : dates})
t = time()
_ = df.date.apply(fmt_date)
time() - t
# 15.647859811782837

# time parapply
t = time()
_ = list(parapply(df.date, fmt_date))
time() - t
# 4.906782865524292
```

I don't get the same kind of speedup w/ the `clean_text` function above, but formatting dates is a reasonable example of an expensive string operation.

**Comment by jayneflux** [comment]
I have a usecase where the function makes an RPC to fetch additional data. In that case, anything that runs concurrently, even just using python threads will result in a win. @jmcarpenter2, instead of hardcoding to use pandas apply, why not let the user override the default fallback choice?

**Comment by jayneflux** [comment]
Thanks for the background! I'm not very familiar with the pandas APIs, I definitely don't have a well thought out proposal in mind. 

This is just me proposing the simplest fix for *my*  problem. I looked at the swifter code a bit, having a second function would work if the API allows for it,. However, I see issues in parallelizing it without providing knobs that control how it would run in parallel (thread counts for example)

Perhaps it's worth implementing what I'm talking about outside the Pandas API/swifter since it doesn't really apply to most conventional uses of Pandas and probably shouldn't be a drop in replacement for the apply call. I'll want something that consumers and emits DataFrame/Series objects though so let me see what my solution looks like and if it belongs in swifter.

**Comment by yoavo1984** [comment]
@jmcarpenter2 
Hi Jason,
I have a question which I would really like to hear your thoughts on.

I'm using a computer with 20 cpus.

I've tried swifter on vectorized numerical dataframes and witnessed a massive improvement on the
running time compare to pandas apply.

As mentioned this failed with text processing dataframes, 
I've also tried ("native" dask and multiprocessing with ProcessPoolExecutor), and as you mentioned
pandas apply had the best/on-par performance.

With multiprocessing & ProcessPoolExecutor, I've manually split the data to 20 and started a process for each chunk.

Do you have any explanation as to how **apply** can achieve a running time comparable to starting 20 processes?

Thanks!

**Comment by jmcarpenter2** [comment]
Hi @yoavo1984,

I am pretty confident that the reason that string operations are unable to take advantage of parallel processes is that strings are immutable. Referencing [this link](https://wiki.python.org/moin/PythonSpeed/PerformanceTips#String_Concatenation),

> you can't say something like, "change all the 'a's to 'b's" in any given string. Instead, you have to create a new string with the desired properties. This continual copying can lead to significant inefficiencies in Python programs.

So I think what is happening under the hood when we try to parallelize a string apply operation is that each core is in fact creating a bunch of new strings. Why this is slower than a single core doing it must do with the communication between cores then, but this is as far as my knowledge goes.

Sorry I can't be of more help to you, but I think this is a good starting point and if anyone else in the community has more knowledge to explain this, it would be greatly appreciated.

**Comment by yoavo1984** [comment]
@jmcarpenter2 
Thank you for taking the time to answer.
I'll keep digging myself and if I find something valuable I'll post it.

**Comment by apurvis** [comment]
Is this why [the code currently always uses Pandas (and not dask) to execute `.apply()` on any dataframe with a string column](https://github.com/jmcarpenter2/swifter/blob/master/swifter/swifter.py#L268)?

(If not, I'm wondering why that limitation exists)

**Comment by jmcarpenter2** [comment]
Everyone, please note the latest update to the package [this PR by @apurvis](https://github.com/jmcarpenter2/swifter/pull/39), which allows an override to the default "don't use dask if there is a string in the dataframe" functionality

**Comment by dmexs** [comment]
> @jmcarpenter2
> Thank you for taking the time to answer.
> I'll keep digging myself and if I find something valuable I'll post it.

@yoavo1984 did you find the manual chunking and threading of your dataframe to be faster than pandas.apply()?

I'm currently using .apply() on a df to perform a lookup function using another. Swifter doesn't seem to make any meaningful improvement in performance from what I can tell (there are strings in my df). I'm wondering if manual chunking and running separate apply()'s would be be more performant.

**Comment by jmcarpenter2** [comment]
For anyone reading this issue --

If you are doing processing on text data and want to try to increase speed with swifter, you should try adding `allow_dask_on_strings()` to your command chain.

For example `df.swifter.allow_dask_on_strings().apply(foo)` will allow swifter to attempt using dask on your text data, which by default is not allowed.

Please see the discussion above for why this is the default. Long story short: it can actually run slower than a pandas apply.

So if you are experiencing a lack of performance boost from swifter and you have text data in your dataframe, try `allow_dask_on_strings()`. It is more likely to increase speed if the text column of the dataframe is only used as a lookup rather than be mutated by the function call itself.

**Comment by vinicius-alves** [comment]
Hello guys
Is there any way around this limitation? I need to do a heavy processing in a text dataframe. I thought about saving each partition of the text columns in a csv file and loading this csv before entering the apply in each process, rebuilding the original dataset.

**Comment by jai-soni** [comment]
Hi Guys, Is there a workaround this issue for text data?

**Comment by stonephoenix** [comment]
I tried using df.swifter.allow_dask_on_strings().apply(foo) to process text (calculating edit distance between two columns) , but it still seems that it is still using one core only, and there is not speed difference compared to df.swifter.apply(foo).

**Comment by renwenbo** [comment]
Any updates on this issue? I've been experiencing this as well.

**Comment by c-shreya** [comment]
Hi @jmcarpenter2, any updates on this issue would be greatly appreciated!
Thanks!

**Comment by jmcarpenter2** [comment]
Hi @c-shreya and all,

The only update I have at this moment is that I have been looking into alternative approaches/back-ends which may help with specific issues that swifter has and features that users strongly desire. For example, this text processing issue has been a longstanding issue for swifter. Additionally, users have been asking for a groupby-apply for a long time as well. 

I am optimistic that other approaches will enable these shortcomings of swifter to be solved or at least improved, but I don't want to promise anything. These are not easy problems to solve and I've found that most out-of-the-box solutions don't help with them.

Thank you all for your patience,
Jason

**Comment by bhaskarnn9** [comment]
> If you are doing processing on text data and want to try to increase speed with swifter, you should try adding `allow_dask_on_strings()` to your command chain.
> 
> For example `df.swifter.allow_dask_on_strings().apply(foo)` will allow swifter to attempt using dask on your text data, which by default is not allowed.

Dask Apply: 100%|██████████| 24/24 [00:02<00:00,  8.34it/s]
CPU times: user 1.21 s, sys: 126 ms, total: 1.34 s
Wall time: 5.08 s

Earlier it was 10 odd secs. Works great for me!! Thanks

**Comment by jmcarpenter2** [comment]
Dear swifter community and @hadyan-tvlk ,

I am very pleased to announce that swifter v1.0.0 was just released. With that release comes a fix for this nearly 2 year old issue. By leveraging modin dataframes specifically to perform axis=1 string applies, we are able to achieve a performance boost when using swifter on dataframes containing string dtype columns.

NOTE: This means that using `allow_dask_on_strings()` is no longer required. In fact, this legacy parameter is likely to slow down your apply performance because it will force swifter to attempt to use dask instead of modin. However, the parameter is kept for (A) backwards compatibility and (B) in case a user prefers the dask functionality.

Please upgrade to swifter 1.0.0 and try it out for yourself. Let me know if (A) it doesn't work for you or (B) it works well for you. Feedback is desired!

`pip install swifter==1.0.0`

Thanks so much for your patience,
Jason

**Comment by jayneflux** [comment]
I haven't been using the library for a while but it's really great to see things resolved with such awesome bug closing notes. Folks like you make the OSS world the magical place that it is.
Thank you so much Jason!

**Comment by erickrf** [comment]
Using swifter (version 1.0.9) actually decreased speed for me too. I did some string operations on a 100k row dataframe. Even tried `allow_dask_on_strings()` but that didn't change much.
