### ISSUE TITLE
LinAlgError while doing df.apply

### ISSUE THREAD

**Issue by benoib** [jmcarpenter2/swifter#141]
Hello,

Sorry in advance if the shape of the issue is not right. I'm trying to replicate Ian Ozsvald talk on pandas speed ups.

see:
https://www.youtube.com/watch?v=I1xyjc-JgGM&t=1254s&ab_channel=OpenDataScience

For details.
Basically I try  to run this function:

![image](https://user-images.githubusercontent.com/5717250/98112014-c34b6c00-1ea1-11eb-9b3d-453a29159ade.png)

On a simple dataframe shape (10000,20)

:
`results_apply = data.swifter.progress_bar(False).apply(lambda row: ols_numpy_raw(row),axis=1,raw=True)`
I get a LinAlgError when swifter tries to vectorise a sample. Which is normal here (it inputs a row of shape (16,20) when (1,20) is expected. But the error not being part of **ERRORS_TO_HANDLE** , it crashes and does not continue.

**Comment by jmcarpenter2** [comment]
Hey @benoib ,

I _could_ add `LinAlgError` to the list of `ERRORS_TO_HANDLE` but it kinda opens up the conversation to... how many different types of custom error types do external packages introduce that swifter needs to handle? And in what cases is it not appropriate to handle all of them?

Instead, if you want to skip the vectorization test, I suggest using the new feature of `swifter`: `force_parallel`, which allows you to skip the swifter algorithm and jump straight to parallelization. Hopefully that helps!

Closing the issue since this is nearly 2 years old (sorry!) - please reopen if further discussion would be helpful
