### ISSUE TITLE
swifter for big data

### ISSUE THREAD

**Issue by showkeyjar** [jmcarpenter2/swifter#144]
I'm so embarrassed that I use swifter to apply very big pandas DataFrame.

but it cause the compute crash, because it used all memory of system.

I also found set_ray_compute(num_cpus, memory) in documents, but it not work

I'm curious, dose swifter can limit the cpu and memory usage?

how can I use swifter safely?

**Comment by showkeyjar** [comment]
so it sames that this project will be deserted?

I found modin can run smoothy, so I use modin solved my problem.

**Comment by jmcarpenter2** [comment]
Hi @showkeyjar,

This project is not deserted. I am the sole maintainer of this project and have been very busy with work lately. I have not had much time recently to help out with your issue. For that I apologize. 

In order to get a quicker response please pose a well formed question with details regarding the specific issue you are encountering. Some things that are useful include: 

* Installed versions of swifter, modin, pandas, dask
* Snippet of code/data to reproduce the error
* Stack trace of error encountered

Thanks,
Jason

**Comment by jmcarpenter2** [comment]
Related to #145 so closing in favor of that one
