### ISSUE TITLE
allow_dask_on_strings(enable=True) error: TypeError: cannot pickle '_thread.lock' object 

### ISSUE THREAD

**Issue by naisanzaa** [jmcarpenter2/swifter#164]
I'm testing out trying to utilize all physical and virtual cores with `allow_dask_on_strings(enable=True)`, but I'm running into the error: 

```
cannot pickle '_thread.lock' object 
```

I'm trying to use `allow_dask_on_strings` based on this user comment (https://github.com/jmcarpenter2/swifter/issues/45#issuecomment-486655130)

Since the function returns a string.

'Forward Dns' dtype is object: 
```
type(df[df['Forward Dns'].notna()].loc[:,'Forward Dns'].dtype)
Out[16]: numpy.dtype[object_]
```

test code:
```
    results = {
        'deviceState': {
            'Forward Dns': df[df['Forward Dns'].notna()]['Forward Dns'].swifter.allow_dask_on_strings(
                enable=True).apply(
                lambda x: c.devices(x)).swifter.apply(
                lambda x: x.df.deviceState.iloc[0] if not x.df.empty else None
            ).rename('deviceState')
        }
    }
```

c.devices:
```
def devices(dict):
    return str
```

**Comment by jmcarpenter2** [comment]
Based on this [stackoverflow post](https://stackoverflow.com/questions/44144584/typeerror-cant-pickle-thread-lock-objects)... my guess is that it's because you are nesting `swifter` applies (or at least trying to run two simultaneously on a single dataset). I believe this can be resolved by separating out the swifter invocations into separate lines of code. Closing now as this issue is nearly a year old
