### ISSUE TITLE
pd.Series.swift.apply out differs from pd.Series.apply where arg is a Series of dictionaries 

### ISSUE THREAD

**Issue by jpau** [jmcarpenter2/swifter#17]
My context: I have a column in my DF, a series of dictionaries, that I want to create another DF from.

The issue is that I expected pd.Series.swift.apply and pd.Series.apply to have the same output.

Let's define a series of dictionaries:

```
aDict = {"a": 1, "b": 2}
bDict = {"a": 3, "b": 4}
s = pd.Series([aDict, bDict])
```

Applying pd.Series.apply to this will create a DataFrame:
`s.apply(pd.Series)`

a | b
-- | --
1 | 2
3 | 4

Whereas applying pd.Series.swifter.apply to this will return the same series of dictionaries:
`s.swifter.apply(pd.Series)`

0    {'a': 1, 'b': 2}
1    {'a': 3, 'b': 4}

**Comment by jmcarpenter2** [comment]
Hi @jpau,

Thanks for raising this issue, and my apologies for the delay in my response. This issue is resolved in version 0.251. Please upgrade to the latest version.

There was a bug in the assertions for shape. It was supposed to check that the sample output shape from an apply aligns with that of the vectorized solution. If not, then move on to the rest of the swifter code.

Unfortunately, instead of checking that the output shape was aligned, it was checking the the input shape was aligned with the output from vectorization.

In your case, this caused it to use a vectorized function when it should have resorted to pandas or dask.

Thanks again for bringing this to my attention!
