### ISSUE TITLE
Can you give a working example with multiple columns and extra arguments

### ISSUE THREAD

**Issue by lstavrogiannis** [jmcarpenter2/swifter#22]
I tried to run the following which should work according to the documentation:
`df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})
def my_sum(a, b):
    return a+b
df[['x'], ['y']].swifter.apply(my_sum)
`

This returns a Pandas error `TypeError: unhashable type: 'list'`, it would be great if you could update the documentation with a working example. Thank you

**Comment by jmcarpenter2** [comment]
@lstavrogiannis, I apologize for taking so long to respond to this. This issue should've been resolved weeks ago. First off, thanks for pointing out that there are no examples of multiple-column applies in the documentation. I have updated the notebook with an example.

There are a few issues with your example. In general, if a pandas apply doesn't work, then a swifter apply won't work.

First off, it should be 
`df[['x', 'y']].swifter.apply(my_sum)`
rather than wrapping lists around each column name in the selection like 
`df[['x'], ['y']].swifter.apply(my_sum)`

Secondly, for column-wise applies on multiple columns, the value that is passed through to the apply function is the entire row. That means you need to specify the columns in the apply function you wish to to use for your apply, e.g. 
`df[['x', 'y']].swifter.apply(lambda row: my_sum(row['x'], row['y']))`
 or since you already defined the columns you wish to sum you can simplify this to 
`df[['x', 'y']].swifter.apply(lambda row: my_sum(*row))`

I presume this is just an example for learning, but if you were really trying to implement this then you could even simplify the third point by using the built-in sum function to 
`df[['x', 'y']].swifter.apply(sum)`
because that function can take in a row.
Alternatively, you could change your my_sum function to be 
```
def my_sum(row):
    return row['x'] + row['y']
```
which would allow you to write your apply code as 
`df[['x', 'y']].swifter.apply(my_sum)`

I hope this clears up how to use applies (either pandas or swifter). Please feel free to reopen the issue if it does not. Thanks for raising the point that there were no examples in the notebook provided. Adding them has improved the quality of the library. As a side note, I also added an example for rolling applies in the notebook as well due to this comment.
