### ISSUE TITLE
groupby_apply doesn't work

### ISSUE THREAD

**Issue by opensorceror** [jmcarpenter2/swifter#23]
Hi,

I have the latest version of swifter. When I try to do `df.swifter.groupby_apply(...)`, I get the following error:
`'DataFrameAccessor' object has no attribute 'groupby_apply'`

However, the docs still contain info on using `groupby_apply`:
https://github.com/jmcarpenter2/swifter/blob/master/examples/swifter_apply_examples.ipynb

Has it been removed from the API recently? If yes, would you recommend another library to parallelize groupby operations?

**Comment by jmcarpenter2** [comment]
Hi @opensorceror,

Ah I should definitely remove groupby_apply from the examples. Yes it was removed from the API because there were very few, if any, situations in which it actually increased speed of processing objectively. 

To be perfectly honest, I'm not sure that arbitrary groupby_apply operations can be increased in speed with parallel processing due to the shuffles that occur when performing arbitrarily complex operations in this manner. Sorry, I wish I could be of more help here.
