### ISSUE TITLE
swifter slower than apply

### ISSUE THREAD

**Issue by SimWdm** [jmcarpenter2/swifter#30]
Hey everyone,

I just tried the swifter apply functionality but for my 577 row pandas DataFrame, it is about 40 times slower than pandas apply. Please refer to the screenshot attached.

Best and thanks in advance
Simon
![image](https://user-images.githubusercontent.com/32895068/48617767-a4dbc580-e997-11e8-9d23-b1a4d5a836ee.png)

**Comment by jmcarpenter2** [comment]
Hi @SimWdm, 

Thank you for notifying us that this has happened. 

The reason that this is happening is that swifter has a small overhead to test whether or not a normal pandas apply is the correct method of transformation to apply. 

In fact, the way that swifter works is that it takes the first 1000 rows (in this case your entire df) and performs 3 tests of the same apply and estimates the time of that apply. Once it has run those tests, it then estimates the duration of the apply on the full data set and depending on that estimate chooses a pandas or a dask apply.

Effectively, swifter had to run your apply 4 times to get the full result. 

This issue only applies to very tiny data sets e.g. < 1000 rows, and is a tradeoff that swifter makes in order to asymptote to optimal performance on all other data sets.

I hope that clears things up!
