### ISSUE TITLE
 TypeError: TypeError('encode() argument 1 must be string, not bool',) while `apply`ing to dataframe

### ISSUE THREAD

**Issue by apurvis** [jmcarpenter2/swifter#38]
**Python 2.7.15**
**Swifter 0.281**
**Pandas 0.24.1**
**Numpy 1.16.1**

Trying to switch a relatively simple currently working dataframe `.apply` to use this package, I ran into this exception.  Here is the code I am running

```python
def score_stuff(df_to_score, months, predictor):
    def compute_value(row):
        return predictor.compute_n_month_values(row.plan, row.length_in_months, row.months)

    df_to_score['output'] = df_to_score.apply(compute_value, axis=1)
```
(`row.plan` is a string/object, `row.length_in_months` is a float, and `row.months` is an int.  There are other cols in the `df_to_score` of many types but they are not referenced in the `compute_value()` method)

Here's the stack trace.

```
File "/opt/airflow/repo/dags/scripts/models/score_stuff.py", line 128, in score_stuff
   df_to_score['output'] = df_to_score.apply(compute_value, axis=1)
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/swifter/swifter.py", line 285, in apply
  **kwds
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 657, in inner
  t = tclass(*targs, total=total, **tkwargs)
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 945, in __init__
  self.display()
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1315, in display
  self.sp(self.__repr__() if msg is None else msg)
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 250, in print_status
  fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 243, in fp_write
  fp.write(_unicode(s))
File "/var/lib/venv/airflow/local/lib/python2.7/site-packages/tqdm/_utils.py", line 160, in write
  self, 'encoding')))
TypeError: encode() argument 1 must be string, not bool
Exception TypeError: TypeError('encode() argument 1 must be string, not bool',) in <bound method tqdm.__del__ of Pandas Apply:   0%|          | 0/14168 [00:00<?, ?it/s]> ignored
```

Interestingly, using `.swifter` was fine on my local OS X machine on a small dataset, but failing on a 16 core EC2 instance with a larger dataset.

I tried passing `raw=True` just in case that might help, but it did not... am i just doing something dumb?

**Comment by apurvis** [comment]
FWIW I just tried limiting my `df_to_score` to just those 3 columns + 1 other integer type `id` column, but still hit the same error.

**Comment by apurvis** [comment]
Seem to have found a workaround by just setting `.progress_bar(False)` when running `.apply()`, but i think this is still unexpected behavior.

**Comment by jmcarpenter2** [comment]
Hi @apurvis,

Thanks for the question, and the PR!

I want to try to understand what's going on here a little bit more before I can help (or merge the PR).

It sounds like you are trying to run swifter on an entire dataframe with mixed data types and are getting (1) an unexpected error related to the progress bar and (2) are losing the performance boost of swifter because one of the columns in the dataframe contains a string.

You correctly identified that swifter is hard-coded not to utilize dask if the object is a string. And that's for good reason, because it is at least as slow as base pandas, usually slower. 

1) My first question is if you could provide more information relevant for debugging. For example, what is the function being called by predictor.compute_n_month_values() and what does it require? Also, how big is the dataframe you are trying to call swifter on for the local machine, and for the EC2?
2) If this function doesn't require the string data type column, why not consider filtering the dataframe down to just the columns you need before calling swifter on the dataframe?

Let me know, and thanks so much for your interest in the package! I'll do my best to respond in a timely manner.

-Jason

**Comment by apurvis** [comment]
> My first question is if you could provide more information relevant for debugging. For example, what is the function being called by `predictor.compute_n_month_values()` and what does it require? Also, how big is the dataframe you are trying to call swifter on for the local machine, and for the EC2?

`predictor` is a class that wraps a dataframe of roughly 1-2k rows.  it's a class that does a lookup in that dataframe (by the string column `row.plan`, specifically) and then applies some basic arithmetic and based on `row.months` and return a float.

> You correctly identified that swifter is hard-coded not to utilize dask if the object is a string. And that's for good reason, because it is at least as slow as base pandas, usually slower.

my impression though was that it was slower for _processing_ strings in a dataframe.  i don't need to do anything to the string except use it in a lookup in another dataframe.  this is a super parallelizable task; each row's return value for `predictor.compute_n_month_values()` is totally independent of all the other values.

> 2. If this function doesn't require the string data type column, why not consider filtering the dataframe down to just the columns you need before calling swifter on the dataframe?

unfortunately it does require it, as mentioned.

i had some success just switching my code from using `swifter` to just using `dask` directly; definitely speeds up the calculations.

**Comment by apurvis** [comment]
> 1. Also, how big is the dataframe you are trying to call swifter on for the local machine, and for the EC2?

sorry i didn't answer this.  I think the error was caused by the inability of a forked process to use the progress bar, and turning off the progress bar fixed the issue.

as far as how big - the dataframe i'm processing is actually pretty small ultimately - like a few million rows.

**Comment by apurvis** [comment]
(if it helps w/r/t the progress bar issue, i was trying to execute this code from Airflow, using the standard [LocalExecutor](https://airflow.apache.org/code.html?highlight=executors#airflow.executors.local_executor.LocalExecutor), which forks a process)

**Comment by jmcarpenter2** [comment]
Thanks for answering all those questions, I understand now.

I completely get the thinking behind your [PR](https://github.com/jmcarpenter2/swifter/pull/39). I will approve it to provide better support for users in this same situation.

As far as the progress bar issue goes: I think that TQDM is getting confused because LocalExecutor is forking processes with the `mulitprocessing` module, but also swifter is forking processes with the `dask` module. 

I'm thinking there may be another solution here: allowing the user to override the default scheduler (and possibly make the default scheduler threads). I will submit a PR to this effect sometime soon

**Comment by apurvis** [comment]
makes sense.  maybe you should just update the `README` to mention that you should disable the progress bar if this is being called from a forked process?

**Comment by jmcarpenter2** [comment]
Done 👍
