### ISSUE TITLE
Attribute Error when using swiftapply over df_groupby

### ISSUE THREAD

**Issue by vruvora** [jmcarpenter2/swifter#4]
![image](https://user-images.githubusercontent.com/4951479/41003844-adf06640-68cc-11e8-9ae7-7d1b1991b0dc.png)

**Comment by summerela** [comment]
I think the swiftapply function was only designed to work on apply statements, not groupby...

**Comment by jmcarpenter2** [comment]
Thanks for suggesting this improvement to the package!

The latest version of swifter now includes a groupby_apply function implemented for whichever is quicker (dask/pandas).

Use it as follows: 
```
import pandas as pd
import swifter

df = pd.DataFrame({'x': [1,2,3,4], 'y':['a','b','a','b']})
df_grouped = df.swifter.groupby_apply('y', lambda x: x.max() - x.min())
df_grouped = df.swifter.groupby_apply(groupby_col, func, *args, **kwds)
```

Unfortunately, in my brief experimentation, I haven't noticed it to be quicker than a regular pandas apply. Hopefully your use case will prove otherwise.
