### ISSUE TITLE
`redirect_stderr` in 0.295 breaks python 2 compatibility

### ISSUE THREAD

**Issue by kr-ish** [jmcarpenter2/swifter#77]
Not sure if this is a known consequence (understandable since python 2.7 EOL is coming soon), but- 0.295 breaks python 2 since `redirect_stderr` doesn't exist in python 2's `contextlib`.

I think [contextlib2](https://contextlib2.readthedocs.io/en/stable/) could be used here- I can make a PR if I find the time, but thought I'd post it here in the interim

**Comment by jmcarpenter2** [comment]
Thanks for catching this @kr-ish!

As you mentioned, [python 2.7 EOL is coming soon](https://pythonclock.org/) (approximately 3 months at the time of writing this response). Not only that, nearly all of the major (and many of the minor) python libraries have [pledged to discontinue support for python 2](https://python3statement.org/). If `swifter` had a logo, I would feel inclined to add it to the list of libraries on that pledge. But either way, I believe that at this time it is okay to break backwards compatibility for python 2.

With that said, if there is a significant need for `swifter` to support python 2.7, whoever requires that should speak up now. If someone has a real need, I'm happy to temporarily implement a patch until whoever requires that version can move to python 3. But after January 1, 2020, it is probably for the best that we don't continue to worry about python 2 compatibility.

Let's leave this issue open for now so that whoever may require such compatibility can speak up and also anyone visiting the library can be aware of the current lack of compatibility.

Thanks again,
Jason

**Comment by jmcarpenter2** [comment]
Python 2.7 end of life (EOL) has come, and as such I believe it is probably safe to close this issue. Thanks again to @kr-ish for raising the issue as I'm sure it helped clarify the issue for visitors to this repo.

Closing...
