### ISSUE TITLE
How to apply row-wise?

### ISSUE THREAD

**Issue by slhck** [jmcarpenter2/swifter#8]
This is more of a support question. I would like to replace a rowwise apply function, e.g.:

```
def foo(row):
    row["bar"] = "baz"
    return row
df = df.apply(foo, axis=1)
```

I tried using `swiftapply` in the same manner:

```
swiftapply(df, foo, axis=1)
```

But the kwarg is just passed to the `foo` function.

Is it possible to use `swiftapply` for rowwise operations, too?

PS: Thanks for offering this tool!

**Comment by jmcarpenter2** [comment]
Hi there,

Thanks so much for your question! That is an important idea to include in the package. 

Please give me a little over a week to get back to you though as I am currently traveling without access to a computer.

I am planning on attempting an overhaul to the package that will allow for a lot more flexibility for the user.

Thanks for your patience!
Jason

**Comment by slhck** [comment]
No worries, thanks a lot for looking into it!

**Comment by jmcarpenter2** [comment]
I got a chance to reread your question and I'm hoping I understand you correctly.

1) You want to make an element-wise operation down each row of a series or dataframe?
or
2) Or do you want to make an element-wise operation across each column of a row?

The current version of swifter only provides support for (1) because dask only provides support for (1), not (2). Hopefully in the future we can allow more flexibility. But if I understand you correctly, then support for what you wish to do already exists. Be sure to update to the latest package and check the README to see how to use it now.

Please let us know if this resolves your issue, thanks!

**Comment by slhck** [comment]
I would like to do 1), that is, apply a custom function on each row of the data frame. In my particular case, the function modifies the entire row and returns that, instead of returning just a series.

I now see that with version 0.200, the syntax was changed and there is no `swiftapply` function anymore. I was therefore looking into the examples and tried to construct an example:

```python
#!/usr/bin/env python3

import pandas as pd
import swifter

data = [
    {"foo": "bar", "xyz": "abc"},
    {"foo": "bar", "xyz": "def"}
]
df = pd.DataFrame(data)

print(df)

def foo(row):
    if row["xyz"] == "abc":
        row["bar"] = "baz"
    else:
        row["baz"] = "bar"
    return row


df2 = df.apply(foo, axis=1)
print(df2)
```

When I try this with swifter, I get:

```
  File "./test.py", line 26, in <module>
    df3 = df.swifter.apply(foo, axis=1)
  File "/Users/werner/.local/share/virtualenvs/best-net-data-analysis-xEhMcwIZ/lib/python3.6/site-packages/swifter/swifter.py", line 100, in apply
    for c in samp.columns], axis=axis)
  File "/Users/werner/.local/share/virtualenvs/best-net-data-analysis-xEhMcwIZ/lib/python3.6/site-packages/swifter/swifter.py", line 100, in <listcomp>
    for c in samp.columns], axis=axis)
  File "./test.py", line 15, in foo
    if row["xyz"] == "abc":
  File "/Users/werner/.local/share/virtualenvs/best-net-data-analysis-xEhMcwIZ/lib/python3.6/site-packages/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/werner/.local/share/virtualenvs/best-net-data-analysis-xEhMcwIZ/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 164, in pandas._libs.index.IndexEngine.get_loc
KeyError: 'xyz'
```

When using `swifter`, the value of `row` is not what I expected – it seems to be the `foo` column:

```
0    bar
1    bar
```

**Comment by jmcarpenter2** [comment]
Hi there @slhck, thanks so much for explaining the issue in full detail. 

Yeah, I figured that given the refactoring of the package required typing df.swifter, I didn't want to make people type df.swifter.swiftapply because it's kind of repetitive, so I simplified to df.swifter.apply

This very thorough explanation really allowed me to dive deep in understanding the shortcomings of the DataFrame apply function that I made. This appears to be working now, so I will close this issue. Please reopen it if you find otherwise.

**Comment by slhck** [comment]
Awesome, now it works as expected, thanks a lot for the quick fix!
