### ISSUE TITLE
Can I use swifter with modin?

### ISSUE THREAD

**Issue by rafwaf** [jmcarpenter2/swifter#93]
As the title says, I want to use Swifter with Modin. Will that work?

Thanks.

**Comment by jmcarpenter2** [comment]
Hi @rafwaf,

Thanks for this question! As of today, `swifter` is not integrated with `modin`. However, this is an intriguing proposal that I believe is worth considering. While I am open to the idea of integrating `swifter` with other python packages, it would require a great deal of work to achieve this with `modin` as they do not have a `modin` dataframe extensions accessors API for me to use, like `pandas` does. I have a question to better understand the value proposition of being able to call `swifter` on a `modin` dataframe before embarking on that path:

`swifter` is an algorithm for optimizing applies on `pandas` dataframes by performing checks on the fastest approach [vectorized/parallelized/regular pandas apply] to applying the function to the dataframe, often which the solution is to use `dask` for parallelized operations on large dataframes. `modin` dataframes already perform parallelized operations for methods which are implemented in the API (currently ~71% pandas API coverage), and fall back to `pandas` operations otherwise. Off the top of my head, I can imagine a couple situations in which using the `swifter` algorithm would be an ideal approach to applying a function to a `modin` dataframe in the fastest manner possible:

- The `modin` dataframe is small and the user should be using `pandas` anyways 
- The fastest solution is simply a vectorized operation

For obvious reasons, the parallelization element of the `swifter` algorithm is absent from the two situations listed above. `Modin` already parallelizes the apply operation, so this key aspect of `swifter` is not very useful for `modin` integration.

My question is: can you think of other use cases that would benefit from integrating `swifter` with `modin`? I would love to learn about various ways that `swifter` can be improved for users, and if a `modin` integration would be really useful it would be great to better understand how. Once I understand more, I will happily implement the changes necessary to achieve this.

Thanks,
Jason

**Comment by devin-petersohn** [comment]
Hi @jmcarpenter2, I maintain Modin and was sent here via a question on our email list.

From the user's perspective, I think the greatest benefit to having Swifter support Modin is the ability to continue dropping Modin in to existing workflows that use Swifter. Modin tries to handle this parallelism issue by controlling the entire dataframe context. There are deeper potential collaborations depending on what your plans are for Swifter, but what I understand is that users who are already using Swifter with pandas would like to replace the pandas calls with Modin without changing their code, to include their Swifter `apply` statements.

I'm happy to answer questions and help facilitate integration if this fits with the direction of Swifter, though I probably can't commit to a lot of engineering work for the next couple of weeks.

**Comment by jmcarpenter2** [comment]
Hi @devin-petersohn,

Thanks so much for adding your perspective, and offer to facilitate integration. I understand better now the purpose of this integration, and have some ideas on approaches to make this integration possible. I would love to work together to make this happen, and am interested in hearing more about the other collaborations you mentioned as well.

Unfortunately, I also won't be able to commit to a lot of engineering work for the 2 weeks between Dec 2 - 15, but there should be time on my end to lay out an implementation plan before the holidays and then complete the integration shortly thereafter.  Let me know how you'd like to proceed.

Thank you,
Jason

**Comment by devin-petersohn** [comment]
Let's sync back up after the holidays. I have a backlog of things to work on between now and then as well so waiting a little will let me get caught up.

**Comment by jmcarpenter2** [comment]
Sounds good!

**Comment by rafwaf** [comment]
Thank you guys for responding so quickly. I hope this becomes a useful collaboration.

**Comment by jmcarpenter2** [comment]
Hi @devin-petersohn,

I know it's been awhile since we last synced about this, but I now have much more spare time to work on this project. I wanted to check in and see if you are still open to collaborating on this joint project to integrate modin dataframes and swifter. Please let me know what you think about this topic.

If you want to continue with this collaboration, perhaps we can setup a more direct line of communication to discuss some this thread of work.

Thanks so much,
Jason

**Comment by devin-petersohn** [comment]
>If you want to continue with this collaboration, perhaps we can setup a more direct line of communication to discuss some this thread of work.

Definitely, let's chat about ideas and direction. You can reach me directly at devin@eecs.berkeley.edu.

**Comment by jmcarpenter2** [comment]
Dear @rafwaf ,

Thanks so much for raising this issue. I am pleased to report that swifter v1.0.0 has just been released.

To install:
`pip install swifter==1.0.0` or `pip install -U swifter`

Not only is swifter now compatible with modin dataframes, but by leveraging modin we are able to achieve performance benefits for swifter's base algorithm. See #14 for a discussion.

NOTE: When using the following code, as of this writing swifter's only benefit to modin dataframes is to attempt to vectorize the operation. This still can lead to a significant performance boost, but I felt it is important to call this out. This is because modin dataframes are already distributed and performant, so there is no reason to move to a different parallelization framework.

```python
import modin.pandas as pd
import swifter

df = pd.DataFrame(...)
df.swifter.apply(...)
```

Thanks again,
Jason

**Comment by rafwaf** [comment]
Thank you very much @jmcarpenter2 and @devin-petersohn . I'm looking forward to giving it a try.

I hope a lot of people get to enjoy the benefits of this new synergy between Modin and Swifter.

All the best,
Rafael
