### ISSUE TITLE
swifter apply on whole dataframe gives error

### ISSUE THREAD

**Issue by ishan-saraswat** [jmcarpenter2/swifter#99]
I installed swifter and was trying to run the example code given in the readme:
```python
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})

# runs on single core
df['x2'] = df['x'].apply(lambda x: x**2)
# runs on multiple cores
df['x2'] = df['x'].swifter.apply(lambda x: x**2)

# use swifter apply on whole dataframe
df['agg'] = df.swifter.apply(lambda x: x.sum() - x.min())
```

It results in the following error:

```TypeError: <lambda>() got an unexpected keyword argument 'broadcast'```

The error occurs in the `df["agg"]` line when we use apply on the whole dataframe

**Comment by ishan-saraswat** [comment]
I'm using pandas version 1.0.0 and swifter version 0.300

**Comment by jmcarpenter2** [comment]
Hi @ishan-saraswat,

Thank you very much for bringing this to my attention. `pandas` v1.0.0 removed deprecated keywords "broadcast" and "reduce". As such, I am updating `swifter` to remove these keywords as well in PR #100 .

Once that is merged, I will post an update here.

Thanks again,
Jason

**Comment by jmcarpenter2** [comment]
It turns out there were a couple changes in pandas v1.0.0 that required some updates to swifter. PR #100 is now merged, which made all of these changes.

The latest version of swifter is `0.301`. Please `pip install swifter==0.301` to upgrade. 

NOTE: there may be some backwards compatibility issues with earlier versions of pandas. Please let me know if you run into these issues.

Thanks!
Jason
